// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAz_oU6-gdX10y3zRwDYp_MlTEBRzESOos',
    appId: '1:38172759846:web:8750c3b52b2b7886c993e7',
    messagingSenderId: '38172759846',
    projectId: 'meetup-planner-44ff3',
    authDomain: 'meetup-planner-44ff3.firebaseapp.com',
    storageBucket: 'meetup-planner-44ff3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGog7Y6dHZeiHdGj6MT7-XxIzpsnklxOE',
    appId: '1:38172759846:android:8de654be78b59c7dc993e7',
    messagingSenderId: '38172759846',
    projectId: 'meetup-planner-44ff3',
    storageBucket: 'meetup-planner-44ff3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh7looBazoU9SzODJbw7C6Pj4Yr6LHnxQ',
    appId: '1:38172759846:ios:427767d25749a1f6c993e7',
    messagingSenderId: '38172759846',
    projectId: 'meetup-planner-44ff3',
    storageBucket: 'meetup-planner-44ff3.appspot.com',
    iosClientId: '38172759846-9dqj18ie1u2pcu00djddbms6a1ii1o4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetupPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh7looBazoU9SzODJbw7C6Pj4Yr6LHnxQ',
    appId: '1:38172759846:ios:427767d25749a1f6c993e7',
    messagingSenderId: '38172759846',
    projectId: 'meetup-planner-44ff3',
    storageBucket: 'meetup-planner-44ff3.appspot.com',
    iosClientId: '38172759846-9dqj18ie1u2pcu00djddbms6a1ii1o4b.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetupPlanner',
  );
}
